# Block Heuristic
The task is to place parcels on a pallett in specific blocks of the same orientation.
The question is how many parcels should be in each block to maximize number of parcels but respect pallett size.
<img src="img/BlockHeuristic.png" width="400">

In [1]:
# parameters
A = 80
B = 120
a = 27
b = 18

In [2]:
block_sides = {
    "A1": b,
    "A2": b,
    "A3": a,
    "B1": a,
    "B2": a,
    "B3": b
}

max_ = {}
for s in block_sides:
    max_[s] = int((A if 'A' in s else B)/block_sides[s])
print(f"maxima: {max_}")

maxima: {'A1': 4, 'A2': 4, 'A3': 2, 'B1': 4, 'B2': 4, 'B3': 6}

In [3]:
import pandas as pd

patterns = []
for i in range(max_["B1"]+1):
    for j in range(max_["A2"]+1):
        patterns.append({
            "A1": int(A/block_sides["A1"]),
            "A2": j,
            "A3": int((A-j*block_sides["A2"])/block_sides["A3"]),
            "B1": i,
            "B2": int((B-i*block_sides["B1"])/block_sides["B2"]),
            "B3": int((B-i*block_sides["B1"])/block_sides["B3"])
        })

# compute number of parcels for each pattern
for p in patterns:
    p["parcels"] = p["A1"]*p["B1"] + p["A2"]*p["B2"] + p["A3"]*p["B3"]

# order the patterns descending by number of parcels
patterns = sorted(patterns, key=lambda item: item["parcels"], reverse=True)

pd.DataFrame(patterns)

    A1  A2  A3  B1  B2  B3  parcels
0    4   1   2   1   3   5       17
1    4   1   2   3   1   2       17
2    4   1   2   0   4   6       16
3    4   4   0   0   4   6       16
4    4   4   0   1   3   5       16
5    4   1   2   2   2   3       16
6    4   4   0   2   2   3       16
7    4   0   2   3   1   2       16
8    4   2   1   3   1   2       16
9    4   4   0   3   1   2       16
10   4   0   2   4   0   0       16
11   4   1   2   4   0   0       16
12   4   2   1   4   0   0       16
13   4   3   0   4   0   0       16
14   4   4   0   4   0   0       16
15   4   2   1   1   3   5       15
16   4   2   1   2   2   3       15
17   4   3   0   3   1   2       15
18   4   2   1   0   4   6       14
19   4   0   2   1   3   5       14
20   4   0   2   2   2   3       14
21   4   3   0   2   2   3       14
22   4   3   0   1   3   5       13
23   4   0   2   0   4   6       12
24   4   3   0   0   4   6       12